######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 7 13:51:37 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT -= gui
QT += network

# Input
HEADERS += Pubnub.h QUnixSocket.h
SOURCES += main.cpp Pubnub.cpp QUnixSocket.cpp
